databaseName: user_db

dataSources:
  ds_master:
    url: jdbc:mysql://ds_master:3306/user_db?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 20
    minPoolSize: 1