services:
  ds_master:
    image: mysql:8.0
    container_name: ds_master
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mynet
    ports:
      - "3316:3306"

  ds_slave_0:
    image: mysql:8.0
    container_name: ds_slave_0
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mynet
    ports:
      - "3317:3306"

  ds_slave_1:
    image: mysql:8.0
    container_name: ds_slave_1
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mynet
    ports:
      - "3318:3306"

  shardingsphere-proxy:
    image: apache/shardingsphere-proxy:5.4.1
    container_name: shardingsphere-proxy
    networks:
      - mynet
    volumes:
      - ./proxy/conf:/opt/shardingsphere-proxy/conf
    ports:
      - "33161:3307"
    restart: always

  springboot-app1:
    build: .
    container_name: springboot-app1
    networks:
      - mynet
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://shardingsphere-proxy:3307/user_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: always

  springboot-app2:
    build: .
    container_name: springboot-app2
    networks:
      - mynet
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://shardingsphere-proxy:3307/user_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - mynet
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

networks:
  mynet: