events {
    worker_connections 1024;
}

http {
    upstream springboot-apps {
        server springboot-app1:8080;
        server springboot-app2:8080;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://springboot-apps;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}